import React from 'react';

interface PrivacyPolicyProps {
  onClose: () => void;
}

const PrivacyPolicy: React.FC<PrivacyPolicyProps> = ({ onClose }) => {
  return (
    <div className="absolute inset-0 z-50 bg-white flex flex-col animate-slide-up">
      <div className="flex items-center justify-between p-4 border-b border-slate-100 bg-white/80 backdrop-blur-sm sticky top-0">
        <h2 className="text-lg font-bold text-slate-800">Privacy Policy</h2>
        <button 
          onClick={onClose}
          className="w-8 h-8 flex items-center justify-center rounded-full bg-slate-100 hover:bg-slate-200 text-slate-600 transition-colors"
        >
          ✕
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-6 text-slate-600 text-sm leading-relaxed space-y-4">
        <p className="text-xs text-slate-400 uppercase tracking-widest font-semibold mb-4">
          Last Updated: May 2025
        </p>

        <section>
          <h3 className="text-slate-900 font-bold mb-1">1. Introduction</h3>
          <p>
            Atmolite ("we", "our", or "us") respects your privacy. This Privacy Policy explains how our application operates regarding your data. Atmolite is a client-side web application.
          </p>
        </section>

        <section>
          <h3 className="text-slate-900 font-bold mb-1">2. Local Storage & Permissions</h3>
          <p>
            Atmolite relies on your device's <strong>Local Storage</strong> to function efficiently. When you start the app, we ask for permission to store data. This allows us to:
          </p>
          <ul className="list-disc pl-5 mt-1 space-y-1">
            <li>Save your personalized User Name.</li>
            <li><strong>Cache City Visuals:</strong> Once a city visual is generated, it is saved on your device for 24 hours. This means if you search the same city again, it loads instantly and saves data.</li>
            <li>Track daily API usage limits.</li>
          </ul>
        </section>

        <section>
          <h3 className="text-slate-900 font-bold mb-1">3. Community Caching</h3>
          <p>
            To optimize performance for everyone, Atmolite may check a shared public repository to see if a visual for your city has already been generated by another user today.
          </p>
          <ul className="list-disc pl-5 mt-1 space-y-1">
            <li>If a visual exists in the community cache, your app will download it instead of generating a new one.</li>
            <li>Your generated visuals may be anonymously uploaded to this shared cache to help other users.</li>
            <li><strong>No personal data</strong> (like your name) is ever uploaded to the community cache. Only the generic city visual and weather condition.</li>
          </ul>
        </section>

        <section>
          <h3 className="text-slate-900 font-bold mb-1">4. Third-Party Services (Google Gemini)</h3>
          <p>
            This application uses the Google Gemini API to retrieve weather data and generate images. When you search for a city, the city name is sent to Google. We do not send your personal name to Google.
          </p>
        </section>

        <section>
          <h3 className="text-slate-900 font-bold mb-1">5. Your Control</h3>
          <p>
            You can revoke storage access or delete your data at any time by clearing your browser's "Site Data" or "Local Storage" settings.
          </p>
        </section>

        <div className="pt-8 text-center">
          <p className="text-xs text-slate-400">Atmolite - Atmospheric World Generator</p>
        </div>
      </div>
      
      <style>{`
        @keyframes slide-up {
          from { transform: translateY(100%); }
          to { transform: translateY(0); }
        }
        .animate-slide-up {
          animation: slide-up 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }
      `}</style>
    </div>
  );
};

export default React.memo(PrivacyPolicy);